// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaBpux_L3YCcLpFH88TE2dMa7nEUAea5o',
    appId: '1:526043519375:web:94a734f6c2e39bf66753fa',
    messagingSenderId: '526043519375',
    projectId: 'dap-tp-final-9d7a4',
    authDomain: 'dap-tp-final-9d7a4.firebaseapp.com',
    storageBucket: 'dap-tp-final-9d7a4.firebasestorage.app',
    measurementId: 'G-ZFJNQ02XG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1kziI_uLPdQY61WKYfepBggbpMnas0tk',
    appId: '1:526043519375:android:e922d3975da508286753fa',
    messagingSenderId: '526043519375',
    projectId: 'dap-tp-final-9d7a4',
    storageBucket: 'dap-tp-final-9d7a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx3myit7YEbynG_Ef0p_l8MzxEbA6xCNQ',
    appId: '1:526043519375:ios:fcbc9d337caef5736753fa',
    messagingSenderId: '526043519375',
    projectId: 'dap-tp-final-9d7a4',
    storageBucket: 'dap-tp-final-9d7a4.firebasestorage.app',
    iosBundleId: 'com.example.tpFinalFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx3myit7YEbynG_Ef0p_l8MzxEbA6xCNQ',
    appId: '1:526043519375:ios:fcbc9d337caef5736753fa',
    messagingSenderId: '526043519375',
    projectId: 'dap-tp-final-9d7a4',
    storageBucket: 'dap-tp-final-9d7a4.firebasestorage.app',
    iosBundleId: 'com.example.tpFinalFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaBpux_L3YCcLpFH88TE2dMa7nEUAea5o',
    appId: '1:526043519375:web:860fc795ee2fa4e36753fa',
    messagingSenderId: '526043519375',
    projectId: 'dap-tp-final-9d7a4',
    authDomain: 'dap-tp-final-9d7a4.firebaseapp.com',
    storageBucket: 'dap-tp-final-9d7a4.firebasestorage.app',
    measurementId: 'G-SFQYMCLFN2',
  );
}
